###
POST http://192.168.0.160:8000/api/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "password123"
}

###
GET http://192.168.0.160:8000/
Accept: application/json

###
